### PR TITLE
implementing tests for specific IP assingment to network

### PR DESCRIPTION
**Pull request by rvalle**

### CODE REVIEW

**Review by resmo — APPROVED** [review]
LGTM, on hold until we updated the simulator

**Comment by rvalle** [comment]
@resmo shall I test also for VPCs?

**Comment by rvalle** [comment]
building the simulator for 4.13.1.0 which is the last LTS, if test pass I will PR there...

**Comment by rvalle** [comment]
@resmo  I assume you are aware but the simulator for the 4.13 LTS does not build due to Python 2 deprecation. Maybe I have a quick look, I guess pinning a version or a dependency might be enough, or perhaps migrating to Python 3 is not that hard.

**Pull request closed without merging**
