### PR TITLE
cs_ip_address: Implement assosiate with given IP address

### LINKED ISSUE #30: Picking a particular IP address for a Network
When using the UI it is possible to select a particular IP to acquire for a Virtual Network.

I have tried to replicate the same functionality with the cs_ip_address module, but it does not work. The documentation states that the IP address is required for the release functionality, and I guess that it is being ignored on acquisition.

For example, consider 123.123.123.123 a public IP address associated with our ACS account.

The following call:

```
    - name: Assign Public IP to DMZ
      cs_ip_address:
        ip_address: 123.123.123.123
        network: dmz
```

Will assign a random IP form the public pull, but not the requested one.

### PR DESCRIPTION
**Pull request by resmo**
Closes #30 
/cc @rvalle 

Todos:

- [x] changelog fragment
- [ ] extend tests (depends on new test simulator image with cloudstack >=4.13) see #33 and #32

### CODE REVIEW

**Comment by rvalle** [comment]
man! that was quick.

**Comment by resmo** [comment]
Waiting for CI to pass, I don't expect this breaks anything for cloudstack <4.13.

**Comment by rvalle** [comment]
I was looking at adding the test. But I am missing the IP range. I don't see anything in cs_common. Where are the ip_ranges?

**Comment by rvalle** [comment]
this seems to be it: https://github.com/ansible/cloudstack-test-container/blob/1.2.0/zones.cfg
Not sure why I am running 1.2.0 I guess my local ansible...
on the tests now...

**Comment by rvalle** [comment]
mmm can't pull here...

**Comment by resmo** [comment]
> mmm can't pull here...

its on quay.io, not on docker hub.

**Comment by resmo** [comment]
Ci passed and I don't have any concerns it could break anything. Merging...

**Review by rvalle — APPROVED** [review]

**Comment by resmo** [comment]
Thanks!

**Pull request merged**
